version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/blablacar
    ports:
      - '8001:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=blablacar_db
      - DB_USER=Yurii
      - DB_PASSWORD=71014
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blablacar_db
      - POSTGRES_USER=Yurii
      - POSTGRES_PASSWORD=71014
  redis:
    image: redis
  celery:
    build: .
    command: celery -A Blablacar worker -l info
    volumes:
      - .:/usr/src/blablacar
    environment:
      - DB_HOST=db
      - DB_NAME=blablacar_db
      - DB_USER=Yurii
      - DB_PASS=71014
    depends_on:
      - db
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A Blablacar beat -l info
    volumes:
      - .:/usr/src/blablacar
    environment:
      - DB_HOST=db
      - DB_NAME=blablacar_db
      - DB_USER=Yurii
      - DB_PASS=71014
    depends_on:
      - db
      - web
      - redis

volumes:
  postgres_data: