version: '3.11'

services:
  web:
    build: .
    command: sh -c "gunicorn Blablacar.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/blablacar
      - static_volume:/usr/src/blablacar/static/
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.production
  redis:
    image: redis
  celery:
    build: .
    command: celery -A Blablacar worker -l info
    volumes:
      - .:/usr/src/blablacar
    env_file:
      - .env.production
    depends_on:
      - db
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A Blablacar beat -l info
    volumes:
      - .:/usr/src/blablacar
    env_file:
      - .env.production
    depends_on:
      - db
      - web
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/blablacar/static/
    ports:
      - "8001:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: