# Generated by Django 4.1.4 on 2023-03-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_slug_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='API_key',
        ),
    ]
