# Generated by Django 4.0.4 on 2022-05-19 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=40, verbose_name='Звідки?')),
                ('to_city', models.CharField(max_length=40, verbose_name='Куди?')),
                ('locale', models.CharField(default='uk-UA', max_length=5, verbose_name='Локалізація')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('start_date_local', models.DateTimeField(default=datetime.datetime.now, verbose_name='Починаючи з часу')),
                ('end_date_local', models.DateTimeField(blank=True, null=True, verbose_name='Закінчуючи часом')),
                ('requested_seats', models.IntegerField(default=1, verbose_name='Кількість місць')),
                ('radius_in_meters', models.IntegerField(blank=True, null=True, verbose_name='Радіус пошуку')),
            ],
            options={
                'verbose_name': 'Поїздка',
                'verbose_name_plural': 'Поїздки',
            },
        ),
    ]
