# Generated by Django 4.0.5 on 2022-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_from_coordinate_alter_task_to_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='radius_in_meters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Радіус пошуку, м'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requested_seats',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість місць'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Загальна кількість знайдених поїздок'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='full_trip_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Загальна кількість знайдених повних поїздок'),
        ),
    ]
