# Generated by Django 4.0.5 on 2022-06-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_radius_in_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='radius_in_meters',
        ),
        migrations.AddField(
            model_name='task',
            name='radius_in_kilometers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Радіус пошуку, км'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.task', verbose_name='Завдання'),
        ),
    ]
