# Generated by Django 4.0.5 on 2022-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0005_alter_task_options_alter_taskinfo_options_and_more'), ('main', '0006_remove_task_radius_in_kilometers_and_more'), ('main', '0007_task_radius_in_kilometers')]

    dependencies = [
        ('main', '0004_remove_task_radius_in_meters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Запланована поїздка', 'verbose_name_plural': 'Заплановані поїздки'},
        ),
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'verbose_name': 'Інформація по запланованій поїздці', 'verbose_name_plural': 'Інформація по запланованих поїздках'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('departure_time',), 'verbose_name': 'Доступна поїздка', 'verbose_name_plural': 'Доступні поїздки'},
        ),
        migrations.AddField(
            model_name='task',
            name='only_from_city',
            field=models.BooleanField(default=False, verbose_name='Пошук тільки у ваказному місті відправлення'),
        ),
        migrations.AddField(
            model_name='task',
            name='only_to_city',
            field=models.BooleanField(default=False, verbose_name='Пошук тільки у ваказному місті прибуття'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='radius_in_kilometers',
        ),
        migrations.AddField(
            model_name='task',
            name='radius_in_meters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Радіус пошуку, м'),
        ),
        migrations.AddField(
            model_name='task',
            name='radius_in_kilometers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Радіус пошуку, км'),
        ),
    ]
