# Generated by Django 4.1.4 on 2023-01-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_options_alter_taskinfo_options_and_more_squashed_0007_task_radius_in_kilometers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='task',
            name='radius_in_kilometers',
        ),
    ]
