# Generated by Django 4.1.4 on 2023-03-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='radius_in_meters',
        ),
        migrations.AddField(
            model_name='task',
            name='radius_in_kilometers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Радіус пошуку, км'),
        ),
    ]
