# Generated by Django 4.1.4 on 2023-03-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_task_radius_in_meters_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
