# Generated by Django 4.1.7 on 2023-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_hash',
            field=models.CharField(default=0, max_length=64, verbose_name='Хеш поїздки'),
            preserve_default=False,
        ),
    ]
